let element;

element = document;
element = document.head;
element = document.body;
element = document.URL;
element = document.characterSet;
element = document.contentType;
element = document.forms;
element = document.forms[0];
element = document.forms[0].id;
element = document.forms[0].method;
element = document.forms[0].action;
element = document.links;
element = document.links[0];
element = document.links[0].id;
element = document.links[0].className;
element = document.links[0].classList;
element = document.images;
element = document.scripts;
element = document.scripts[2];
